### ISSUE TITLE
Server crash on boot

### ISSUE THREAD

**Issue by Micaxs** [TerraFirmaGreg-Team/Modpack-Modern#445]
### Version modpack Used

0.2.17

### Environment

Forge Server

### Side Crashed

Server

### New Worlds

No

### Steps to Reproduce

Start server and failed to start

### Crash Report
```

[18:53:59] [Worker-Main-24/ERROR] [minecraft/TagLoader]: Not a JSON object: "firmaciv:sloop_construction/acacia/firmaciv:sloop_construction/ash/firmaciv:sloop_construction/aspen/firmaciv:sloop_construction/birch/firmaciv:sloop_construction/blackwood/firmaciv:sloop_construction/chestnut/firmaciv:sloop_construction/douglas_fir/firmaciv:sloop_construction/hickory/firmaciv:sloop_construction/kapok/firmaciv:sloop_construction/mangrove/firmaciv:sloop_construction/maple/firmaciv:sloop_construction/oak/firmaciv:sloop_construction/palm/firmaciv:sloop_construction/pine/firmaciv:sloop_construction/rosewood/firmaciv:sloop_construction/sequoia/firmaciv:sloop_construction/spruce/firmaciv:sloop_construction/sycamore/firmaciv:sloop_construction/white_cedar/firmaciv:sloop_construction/willow"
[18:53:59] [Worker-Main-24/ERROR] [minecraft/TagLoader]: Couldn't read tag list carryon:entity_blacklist from carryon:tags/entity_types/entity_blacklist.json in data pack FirmaCivilization-0.2.10-alpha-1.20.1.jar
java.lang.RuntimeException: Not a JSON object: "firmaciv:sloop_construction/acacia/firmaciv:sloop_construction/ash/firmaciv:sloop_construction/aspen/firmaciv:sloop_construction/birch/firmaciv:sloop_construction/blackwood/firmaciv:sloop_construction/chestnut/firmaciv:sloop_construction/douglas_fir/firmaciv:sloop_construction/hickory/firmaciv:sloop_construction/kapok/firmaciv:sloop_construction/mangrove/firmaciv:sloop_construction/maple/firmaciv:sloop_construction/oak/firmaciv:sloop_construction/palm/firmaciv:sloop_construction/pine/firmaciv:sloop_construction/rosewood/firmaciv:sloop_construction/sequoia/firmaciv:sloop_construction/spruce/firmaciv:sloop_construction/sycamore/firmaciv:sloop_construction/white_cedar/firmaciv:sloop_construction/willow"
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
        at net.minecraft.tags.TagLoader.m_144495_(TagLoader.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:gtceu.mixins.json:TagLoaderMixin,pl:mixin:APP:kubejs-common.mixins.json:TagLoaderMixin,pl:mixin:APP:tfc.mixins.json:TagLoaderMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:TagLoaderMixin,pl:mixin:A}
        at net.minecraft.tags.TagLoader.m_203900_(TagLoader.java:114) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:gtceu.mixins.json:TagLoaderMixin,pl:mixin:APP:kubejs-common.mixins.json:TagLoaderMixin,pl:mixin:APP:tfc.mixins.json:TagLoaderMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:TagLoaderMixin,pl:mixin:A}
        at net.minecraft.tags.TagManager.m_203920_(TagManager.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:TagManagerMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:TagManagerMixin,pl:mixin:APP:gtceu.mixins.json:TagManagerMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
[18:53:59] [Worker-Main-4/INFO] [KubeJS Server/]: [minecraft:fluid] Found 609 tags, added 77 objects, removed 0 objects
[18:54:00] [Worker-Main-18/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:megacells:blocks/mega_emc_interface
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'megacells:mega_emc_interface'
        at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:145) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
        at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:145) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:153) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871) ~[forge-1.20.1-47.2.6-universal.jar%23348!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
        at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848) ~[forge-1.20.1-47.2.6-universal.jar%23348!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
        at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?] {re:mixin}
        at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
[18:54:00] [Worker-Main-18/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:expatternprovider:blocks/ex_emc_interface
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'expatternprovider:ex_emc_interface'
        at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:145) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
        at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:145) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:153) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871) ~[forge-1.20.1-47.2.6-universal.jar%23348!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
        at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848) ~[forge-1.20.1-47.2.6-universal.jar%23348!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
        at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?] {re:mixin}
        at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
[18:54:00] [Worker-Main-5/INFO] [KubeJS Server/]: [minecraft:block] Found 1662 tags, added 476 objects, removed 0 objects
[18:54:00] [Worker-Main-5/ERROR] [minecraft/TagLoader]: Couldn't load tag [gcyr:uev_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar), gcyr:uiv_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar), gcyr:uxv_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar), gcyr:opv_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar)] as it is missing following references: gcyr:uev_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar), 
        gcyr:uiv_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar), 
        gcyr:uxv_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar), 
        gcyr:opv_oxygen_spreader (from gcyr-1.20.1-0.1.8.jar)
[18:54:01] [Worker-Main-17/INFO] [KubeJS Server/]: [minecraft:item] Found 6360 tags, added 3507 objects, removed 0 objects
[18:54:01] [main/WARN] [minecraft/Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.m_5456_()" because "p_248695_" is null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?] {re:mixin}
        at net.minecraft.server.Main.main(Main.java:195) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.6.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.6.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.6.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.m_5456_()" because "p_248695_" is null
        at net.minecraft.data.loot.BlockLootSubProvider.m_246108_(BlockLootSubProvider.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,pl:accesstransformer:B}
        at com.gregtechceu.gtceu.core.MixinHelpers.lambda$generateGTDynamicLoot$23(MixinHelpers.java:189) ~[gtceu-1.20.1-1.2.3.a.jar%23274!/:?] {re:mixin,re:classloading}
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar%2374!/:?] {}
        at com.gregtechceu.gtceu.core.MixinHelpers.lambda$generateGTDynamicLoot$24(MixinHelpers.java:174) ~[gtceu-1.20.1-1.2.3.a.jar%23274!/:?] {re:mixin,re:classloading}
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar%2374!/:?] {}
        at com.gregtechceu.gtceu.core.MixinHelpers.generateGTDynamicLoot(MixinHelpers.java:171) ~[gtceu-1.20.1-1.2.3.a.jar%23274!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.storage.loot.LootDataManager.handler$bnp000$gtceu$injectLootTables(LootDataManager.java:2525) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at net.minecraft.world.level.storage.loot.LootDataManager.m_278787_(LootDataManager.java) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at net.minecraft.world.level.storage.loot.LootDataManager.m_278738_(LootDataManager.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:LootTablesMixin,pl:mixin:APP:placebo.mixins.json:LootTablesMixin,pl:mixin:APP:railways.mixins.json:MixinLootDataManager,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:gtceu.mixins.json:LootDataManagerMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerForgeMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
        at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
        at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
        at net.minecraft.server.Main.main(Main.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:A}
        ... 13 more
```

**Comment by Micaxs** [comment]
Reinstall of server fixed the issue at hand, not sure what the root cause is.
